import type { Metadata } from "next";
import { Madimi_One } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const madimi = Madimi_One({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${madimi.className} antialiased  `}>
        {" "}
        <Header /> {children} <Footer />
      </body>
    </html>
  );
}
